# Generated by Django 2.2.7 on 2019-12-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='exampletags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
