# Generated by Django 2.2.7 on 2020-01-13 05:18

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20200113_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='madeat',
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'instagram'), ('upload', 'upload')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='madeby',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('post', 'post')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=base.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
