# Generated by Django 2.2.7 on 2020-01-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200114_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='suspicous',
            new_name='suspicious',
        ),
    ]
