# Generated by Django 2.2.7 on 2020-01-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_instapost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='madeby',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('post', 'post')], default='post', max_length=20, null=True),
        ),
    ]
