# Generated by Django 2.2.7 on 2020-01-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200117_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsedPhoto',
            new_name='UploadPost',
        ),
    ]
