# Generated by Django 2.2.7 on 2020-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200120_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
