# Generated by Django 2.2.7 on 2020-01-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Session'),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
