# Generated by Django 2.2.7 on 2020-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200128_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contextdone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tagdone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
