# Generated by Django 2.1.15 on 2020-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20200128_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='starttime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
